import type { VerificationResult } from "@/lib/types";

// A fixed, hand-written example so visitors can see a real report shape before
// signing up. Not fetched from the API — kept static and clearly labeled as such.
export const EXAMPLE_REPORT: VerificationResult = {
  id: "example",
  user_id: null,
  input_type: "text",
  input_raw:
    "This phone has a 5000mAh battery, supports 65W charging, is waterproof, and has a 2-day battery life.",
  user_question: "Are these specs accurate?",
  mode: "CLAIM_CHECK",
  title: "Phone battery and charging specification claims",
  verdict: "PARTIALLY_SUPPORTED",
  risk_level: null,
  confidence: {
    overall: 62,
    evidence_strength: "Moderate",
    independent_source_count: 3,
    primary_source_count: 1,
    contradiction_count: 1,
    last_verified: "2026-08-29T00:00:00Z",
  },
  summary:
    "2 of 4 claims are supported by the evidence found. 1 claim is contradicted by conflicting sources. 1 claim could not be independently confirmed.",
  claims: [
    {
      id: "CLAIM-001",
      text: "Battery capacity is 5000mAh.",
      claim_type: "numerical",
      status: "SUPPORTED",
      evidence_for: ["EVIDENCE-001"],
      evidence_against: [],
      evidence_context: [],
      confidence: 88,
      rationale: "EVIDENCE-001 (manufacturer specification page) states the battery capacity as 5000mAh, matching the claim exactly.",
      time_sensitive: false,
    },
    {
      id: "CLAIM-002",
      text: "Supports 65W charging.",
      claim_type: "technical",
      status: "CONTRADICTED",
      evidence_for: [],
      evidence_against: ["EVIDENCE-002", "EVIDENCE-003"],
      evidence_context: [],
      confidence: 20,
      rationale: "EVIDENCE-002 (manufacturer page) lists 33W max charging; EVIDENCE-003 (independent review) measured 32W in testing. Neither source supports a 65W figure.",
      time_sensitive: false,
    },
    {
      id: "CLAIM-003",
      text: "The device is waterproof.",
      claim_type: "product",
      status: "INSUFFICIENT_EVIDENCE",
      evidence_for: [],
      evidence_against: [],
      evidence_context: ["EVIDENCE-004"],
      confidence: 15,
      rationale: "No official IP rating was found. EVIDENCE-004 only confirms 'splash resistance' language, which is not the same as a tested waterproof rating.",
      time_sensitive: false,
    },
    {
      id: "CLAIM-004",
      text: "Battery lasts 2 days.",
      claim_type: "subjective",
      status: "UNVERIFIED",
      evidence_for: [],
      evidence_against: [],
      evidence_context: [],
      confidence: 0,
      rationale: "Battery life depends heavily on individual usage patterns — treated as a marketing claim, not an objectively verifiable fact.",
      time_sensitive: false,
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-001",
      claim_id: "CLAIM-001",
      source_id: "SOURCE-1",
      excerpt: "Battery: 5000 mAh (typical)",
      relationship: "SUPPORTS",
      why_it_matters: "This is the manufacturer's own published specification sheet.",
      extracted_at: "2026-08-29T00:00:00Z",
    },
    {
      id: "EVIDENCE-002",
      claim_id: "CLAIM-002",
      source_id: "SOURCE-1",
      excerpt: "Charging: 33W wired fast charging",
      relationship: "CONTRADICTS",
      why_it_matters: "Directly conflicts with the claimed 65W charging speed.",
      extracted_at: "2026-08-29T00:00:00Z",
    },
    {
      id: "EVIDENCE-003",
      claim_id: "CLAIM-002",
      source_id: "SOURCE-2",
      excerpt: "In our lab tests, the device peaked at 32W and took 68 minutes to charge fully.",
      relationship: "CONTRADICTS",
      why_it_matters: "An independent lab measurement corroborates the manufacturer's lower figure.",
      extracted_at: "2026-08-29T00:00:00Z",
    },
    {
      id: "EVIDENCE-004",
      claim_id: "CLAIM-003",
      source_id: "SOURCE-3",
      excerpt: "Designed to resist light splashes and rain.",
      relationship: "CONTEXT",
      why_it_matters: "Splash resistance is not equivalent to a certified waterproof (IP) rating.",
      extracted_at: "2026-08-29T00:00:00Z",
    },
  ],
  sources: [
    {
      id: "SOURCE-1",
      url: "https://example-manufacturer.com/specs",
      domain: "example-manufacturer.com",
      title: "Official specification sheet",
      source_type: "official",
      author: null,
      published_at: "2026-06-01T00:00:00Z",
      retrieved_at: "2026-08-29T00:00:00Z",
      quality_score: 78,
      quality_factors: { source_type: "official (base 70)", independence: "Same entity as the subject being verified (-15)" },
      independent: false,
    },
    {
      id: "SOURCE-2",
      url: "https://example-reviews.com/phone-review",
      domain: "example-reviews.com",
      title: "Independent lab review",
      source_type: "independent_publication",
      author: "Review Staff",
      published_at: "2026-07-15T00:00:00Z",
      retrieved_at: "2026-08-29T00:00:00Z",
      quality_score: 90,
      quality_factors: { source_type: "independent_publication (base 82)", independence: "Independent (+8)" },
      independent: true,
    },
    {
      id: "SOURCE-3",
      url: "https://example-retailer.com/listing",
      domain: "example-retailer.com",
      title: "Retailer product listing",
      source_type: "commercial",
      author: null,
      published_at: "2026-05-20T00:00:00Z",
      retrieved_at: "2026-08-29T00:00:00Z",
      quality_score: 45,
      quality_factors: { source_type: "commercial (base 50)" },
      independent: true,
    },
  ],
  contradictions: [
    {
      claim_id: "CLAIM-002",
      evidence_id_a: "EVIDENCE-002",
      evidence_id_b: "EVIDENCE-003",
      description:
        "The claimed 65W charging speed is contradicted by both the manufacturer's own spec (33W) and an independent lab measurement (32W).",
      resolution_note: null,
    },
  ],
  open_questions: [
    'We found no independent evidence confirming a tested IP (waterproof) rating for this device.',
    "Real-world battery life ('2-day battery life') depends on usage and could not be independently verified.",
  ],
  next_actions: [
    "Ask the seller for the device's official IP rating certificate, not just marketing language.",
    "Check the manufacturer's official specification page directly for the charging wattage.",
    "Treat the '2-day battery life' claim as a general marketing statement, not a guarantee.",
  ],
  degraded_providers: [],
  image_analysis: null,
  created_at: "2026-08-29T00:00:00Z",
  updated_at: "2026-08-29T00:00:00Z",
  tags: [],
  notes: null,
  saved: false,
};
